### ISSUE TITLE
Stanford NLP error:

### ISSUE THREAD

**Issue by sushma-ananda** [fpecune/MUF-inMind-April2017-master#10]
2017-06-09 18:08:47,135 INFO    SaraOrchestratorEx15           - 9d2927b5aee855d4   ASR - > utterance: hello  confidence: 0.9876290559768677
2017-06-09 18:08:47,136 INFO    RapportEstimator               - 9d2927b5aee855d4   RapportComponent. These objects have been updated at the blackboard: [status: ELEMENT_ADDED, id: MSG_ASR, element: Component: class edu.cmu.inmind.multiuser.common.model.ASROutput Utterance: hello confidence: 0.9876290559768677]
2017-06-09 18:08:47,144 INFO    TaskReasonerComponent          - 9d2927b5aee855d4   TaskReasoner: MSG_DM Component: class edu.cmu.inmind.multiuser.common.model.DMOutput System Action: ask_genres
2017-06-09 18:08:47,169 INFO    RapportEstimator               - 9d2927b5aee855d4   Input: hello
2017-06-09 18:08:47,696 INFO    SocialReasonerComponent        - 9d2927b5aee855d4   Input: ask_genres, Output: ASN_SYSTEM_CS
2017-06-09 18:08:47,698 INFO    NLGComponent                   - 9d2927b5aee855d4   NLG srOutput: Component: class edu.cmu.inmind.multiuser.common.model.SROutput System Action: ask_genres Strategy:ASN_SYSTEM_CS
Exception in thread “Thread-5” edu.stanford.nlp.io.RuntimeIOException: Could not connect to server: localhost:9000
    at edu.stanford.nlp.pipeline.StanfordCoreNLPClient$2.run(StanfordCoreNLPClient.java:393)
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at java.net.Socket.connect(Socket.java:538)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
    at edu.stanford.nlp.pipeline.StanfordCoreNLPClient$2.run(StanfordCoreNLPClient.java:374)

**Comment by sushma-ananda** [comment]
This issue is fixed by setting up Stanford NLP binaries and starting NLP on 9000 port locally or remote host and update ipaddress /localhost before running the MUF Sara.
