### ISSUE TITLE
Request for alternative: errors setting up MITIE libraries on macOS and cannot run pythonDM on a MacOS for whole pipeline testing and debugging

### ISSUE THREAD

**Issue by sushma-ananda** [fpecune/MUF-inMind-April2017-master#14]
1) When installing by script/requirements , by following command, MITIE installation fails with error log (MITIE_PIP_INSTALLATION_ERROR.rtf)
           pip3 install git+https://github.com/mit-nlp/MITIE.git  
2) So installed using “brew install mitie” , runs successfully. (mitie 0.4 version gets installed)
3) Now when I run “sh run.sh” from DialoguePython, fails to start with attached error (starting.pythonDM.rtf)

Efforts spent in setting this on MacOS: 18 hours.

We should have some alternative solution to address this to avoid a dependency on developers for deploying or integration tests.

[MITIE_PIP_INSTALLATION_ERROR.docx](https://github.com/fpecune/MUF-inMind-April2017-master/files/1066636/MITIE_PIP_INSTALLATION_ERROR.docx)
[starting_pythonDM.docx](https://github.com/fpecune/MUF-inMind-April2017-master/files/1066640/starting_pythonDM.docx)

**Comment by yulundu** [comment]
Hi sushma,

I just created a new branch 'sushma' in the project which tries to remove the dependency of MITIE package. Could you please try the branch?

thanks

**Comment by sushma-ananda** [comment]
HI Yulun,

Thanks for creating a branch. As per my test, I tried running "sh run.sh " it seems I get following error:

dinnerhang-lm:DialoguePython sakoju$ sh run.sh 
Traceback (most recent call last):
  File "Main.py", line 4, in <module>
    from session.SessionManager import SessionManager
  File "/Users/sakoju/Development/inmind/DialoguePython/session/SessionManager.py", line 7, in <module>
    from session.Session import Session
  File "/Users/sakoju/Development/inmind/DialoguePython/session/Session.py", line 5, in <module>
    from dialogue.NLU import NLU
  File "/Users/sakoju/Development/inmind/DialoguePython/dialogue/NLU.py", line 14, in <module>
    from dialogue.nlu.data_router import DataRouter, InvalidModelError
  File "/Users/sakoju/Development/inmind/DialoguePython/dialogue/nlu/data_router.py", line 17, in <module>
    from nlu import registry
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nlu-0.0.0-py3.6.egg/nlu/registry.py", line 21, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nlu-0.0.0-py3.6.egg/nlu/utils/mitie_utils.py", line 6, in <module>
ModuleNotFoundError: No module named 'mitie'

Do you suggest I must configure something here to get script to running ?

**Comment by yulundu** [comment]
I don't know if you have successfully uninstalled nlu before you installed the new version. So here is what I did:

pip3 uninstall nlu
python3 setup.py -install
sh install.sh 

Do the three commands in the right directory. Let me know if it works.

**Comment by sushma-ananda** [comment]
Hi Yulun:

commands:

when I execute all the three commands as you suggested and when i run sh run.sh again:

I get following error: dinnerhang-lm:DialoguePython sakoju$ sh run.sh 
Traceback (most recent call last):
  File "Main.py", line 4, in <module>
    from session.SessionManager import SessionManager
  File "/Users/sakoju/Development/inmind/DialoguePython/session/SessionManager.py", line 7, in <module>
    from session.Session import Session
  File "/Users/sakoju/Development/inmind/DialoguePython/session/Session.py", line 5, in <module>
    from dialogue.NLU import NLU
  File "/Users/sakoju/Development/inmind/DialoguePython/dialogue/NLU.py", line 14, in <module>
    from dialogue.nlu.data_router import DataRouter, InvalidModelError
  File "/Users/sakoju/Development/inmind/DialoguePython/dialogue/nlu/data_router.py", line 17, in <module>
    from nlu import registry
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nlu-0.0.0-py3.6.egg/nlu/registry.py", line 21, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nlu-0.0.0-py3.6.egg/nlu/utils/mitie_utils.py", line 6, in <module>
ModuleNotFoundError: No module named 'mitie'


Am I missing some other configuration  here ?

**Comment by sushma-ananda** [comment]
install.sh tries to install mitie and still getting following error for install.sh:

i-build/setup.py", line 10, in run
        subprocess.check_call(['make', 'mitielib'])
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'mitielib']' returned non-zero exit status 2.
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/sv/lx4gl6gj3713xr_sxpscfy38002wfq/T/pip-9q4zs6li-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/sv/lx4gl6gj3713xr_sxpscfy38002wfq/T/pip-iafiaoyw-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/sv/lx4gl6gj3713xr_sxpscfy38002wfq/T/pip-9q4zs6li-build/

**Comment by yulundu** [comment]
You could comment out mitie install line in install.sh..

Are you at GHC so that I could look at your computer? It works on my computer....

**Comment by sushma-ananda** [comment]
Hi yulun, I tried this solution. Ohh, sure when is a good time to meet today? am at articulate till afternoon today.

**Comment by sushma-ananda** [comment]
Great, this works now, thanks @yulundu ! 
**Summary of the Solution:**
 
1. clone sushma branch from repo https://github.com/yulundu/inmind.git and make sure 
git log contains "4533be3b55f3e8b1c5dacd2399ab4b5de1c84e00" this commit # and comment "initial push" to verify you are having latest commit.
2. run following commands from inside DialoguePython -> dialogue folder 
pip3 uninstall nlu
python3 setup.py install
sh install.sh
**Note**: incase you get permission denied errors, please prefix sudo to above commands.
3. After successfully completing above commands, go back to DialoguePython folder and execute following command:
sh run.sh
4. Now update in MUF-Sara inside config.properties as follows:
#DM
pythonDialogueAddress=tcp://localhost:5590
5. compile and run MUF Sara to use the local python DM instance.

**Comment by sushma-ananda** [comment]
resolved.
