### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException from SocialReasoner + Rapport error

### ISSUE THREAD

**Issue by sushma-ananda** [fpecune/MUF-inMind-April2017-master#19]
whenever MSG_DM is received Social Reasoner processes the request and following error trace is received:

java.lang.ArrayIndexOutOfBoundsException: 12
	at edu.cmu.inmind.multiuser.socialreasoner.control.bn.BehaviorNetworkPlus.getModuleNamesByHighestActivation(BehaviorNetworkPlus.java:820)
	at edu.cmu.inmind.multiuser.socialreasoner.control.reasoners.SocialReasoner.execute(SocialReasoner.java:95)
	at edu.cmu.inmind.multiuser.socialreasoner.control.MainController.process(MainController.java:117)
	at edu.cmu.inmind.multiuser.socialreasoner.control.MainController.addSystemIntent(MainController.java:422)
	at edu.cmu.inmind.multiuser.sara.component.SocialReasonerComponent.selectStrategy(SocialReasonerComponent.java:89)
	at edu.cmu.inmind.multiuser.sara.component.SocialReasonerComponent.onEvent(SocialReasonerComponent.java:138)
	at edu.cmu.inmind.multiuser.controller.blackboard.Blackboard$1.run(Blackboard.java:241)
+++++++++++++++++++ NONE_SYSTEM_CS
+++++++++++++++++++ NONE_SYSTEM_CS
2017-06-13 13:05:35,638 DEBUG   Broker                         - received message [ 04 ] is for orchestrator
2017-06-13 13:05:35,638 DEBUG   Broker                         - sending to worker worker 0067B82D41 for service service session-manager with address 0067B82D41 and expiration 1497373548138
+++++++++++++++++++ NONE_SYSTEM_CS
java.lang.ArrayIndexOutOfBoundsException: -1
	at edu.cmu.inmind.multiuser.socialreasoner.control.util.Utils.exchange(Utils.java:337)
	at edu.cmu.inmind.multiuser.socialreasoner.control.reasoners.SocialReasoner.execute(SocialReasoner.java:97)
	at edu.cmu.inmind.multiuser.socialreasoner.control.MainController.process(MainController.java:117)
	at edu.cmu.inmind.multiuser.socialreasoner.control.MainController.addSystemIntent(MainController.java:422)
	at edu.cmu.inmind.multiuser.sara.component.SocialReasonerComponent.selectStrategy(SocialReasonerComponent.java:89)
	at edu.cmu.inmind.multiuser.sara.component.SocialReasonerComponent.onEvent(SocialReasonerComponent.java:138)
	at edu.cmu.inmind.multiuser.controller.blackboard.Blackboard$1.run(Blackboard.java:241)
+++++++++++++++++++ NONE_SYSTEM_CS
java.lang.ArrayIndexOutOfBoundsException: -1
	at edu.cmu.inmind.multiuser.socialreasoner.control.util.Utils.exchange(Utils.java:337)
	at edu.cmu.inmind.multiuser.socialreasoner.control.reasoners.SocialReasoner.execute(SocialReasoner.java:97)
	at edu.cmu.inmind.multiuser.socialreasoner.control.MainController.process(MainController.java:117)
	at edu.cmu.inmind.multiuser.socialreasoner.control.MainController.addSystemIntent(MainController.java:422)
	at edu.cmu.inmind.multiuser.sara.component.SocialReasonerComponent.selectStrategy(SocialReasonerComponent.java:89)
	at edu.cmu.inmind.multiuser.sara.component.SocialReasonerComponent.onEvent(SocialReasonerComponent.java:138)
	at edu.cmu.inmind.multiuser.controller.blackboard.Blackboard$1.run(Blackboard.java:241)
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at edu.cmu.inmind.multiuser.socialreasoner.control.bn.BehaviorNetworkPlus.activateBehavior(BehaviorNetworkPlus.java:625)
	at edu.cmu.inmind.multiuser.socialreasoner.control.bn.BehaviorNetworkPlus.selectBehavior(BehaviorNetworkPlus.java:734)
	at edu.cmu.inmind.multiuser.socialreasoner.control.reasoners.SocialReasoner.execute(SocialReasoner.java:87)
	at edu.cmu.inmind.multiuser.socialreasoner.control.MainController.process(MainController.java:117)
	at edu.cmu.inmind.multiuser.socialreasoner.control.MainController.addSystemIntent(MainController.java:422)
	at edu.cmu.inmind.multiuser.sara.component.SocialReasonerComponent.selectStrategy(SocialReasonerComponent.java:89)
	at edu.cmu.inmind.multiuser.sara.component.SocialReasonerComponent.onEvent(SocialReasonerComponent.java:138)
	at edu.cmu.inmind.multiuser.controller.blackboard.Blackboard$1.run(Blackboard.java:241)
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at edu.cmu.inmind.multiuser.socialreasoner.control.bn.BehaviorNetworkPlus.triggerPostconditions(BehaviorNetworkPlus.java:636)
	at edu.cmu.inmind.multiuser.socialreasoner.control.bn.BehaviorNetworkPlus.execute(BehaviorNetworkPlus.java:759)
	at edu.cmu.inmind.multiuser.socialreasoner.control.reasoners.SocialReasoner.execute(SocialReasoner.java:116)
	at edu.cmu.inmind.multiuser.socialreasoner.control.MainController.process(MainController.java:117)
	at edu.cmu.inmind.multiuser.socialreasoner.control.MainController.addSystemIntent(MainController.java:422)
	at edu.cmu.inmind.multiuser.sara.component.SocialReasonerComponent.selectStrategy(SocialReasonerComponent.java:89)
	at edu.cmu.inmind.multiuser.sara.component.SocialReasonerComponent.onEvent(SocialReasonerComponent.java:138)
	at edu.cmu.inmind.multiuser.controller.blackboard.Blackboard$1.run(Blackboard.java:241)
2017-06-13 13:05:37,522 DEBUG   Broker                         - received message [ 04 ] is for orchestrator
2017-06-13 13:05:38,192 DEBUG   Broker                         - received message [ 04 ] is for orchestrator

**Comment by sushma-ananda** [comment]
@yoichimatsuyama I have raised this issue as per discussing with @fpecune, but is indeed strange that I was not able to replicate this now from a latest server version. Hence closing this.
