### ISSUE TITLE
Beat error executing the pipeline with MUF server and mockclient/android app

### ISSUE THREAD

**Issue by sushma-ananda** [fpecune/MUF-inMind-April2017-master#42]
MUF never generates a BEAT sentence due to following error:
The reason for this null pointer exception is: the line 995 in XMLWrapper within 
method applyTransform() 
		
line 995: xsl.getTransformer().transform(new DOMSource(xml),result);

2017-09-01 18:10:25,173 INFO    NLGComponent                   - 9d2927b5aee855d4	NLG srOutput: Component: class edu.cmu.inmind.multiuser.common.model.SROutput System Action: ask_genres Strategy:ASN_SYSTEM_CS

XML-22000: (Error) Error while parsing XSL file (Error in expression: '/|*|@*|text()'.).
XML-22900: (Fatal Error) An internal error condition occurred.
java.lang.NullPointerException
	at beat.languageProcessing.LanguageModule.transduce(LanguageModule.java:1136)
	at beat.utilities.BeatModule.process(BeatModule.java:116)
	at beat.BEAT.startProcess(BEAT.java:146) at edu.cmu.inmind.multiuser.sara.component.NLGComponent.extractAndProcess(NLGComponent.java:67) at edu.cmu.inmind.multiuser.sara.component.NLGComponent.onEvent(NLGComponent.java:80)
	at edu.cmu.inmind.multiuser.controller.blackboard.Blackboard$1.run(Blackboard.java:243)

**And this exception is caught by another calling method (convertFromNLPDocument) from LanguageModel.java in line 1043 . Screenshot as follows:**

![screen shot 2017-09-01 at 6 36 38 pm](https://user-images.githubusercontent.com/8979477/29990008-007c89dc-8f45-11e7-8d2f-25b40ffdb754.png)

**Comment by smaskell** [comment]
@yoichimatsuyama any idea what's going on here?

**Comment by timobaumann** [comment]
@yoichimatsuyama , can you take a look what the error is that Sushma runs into?
