### ISSUE TITLE
Beat error

### ISSUE THREAD

**Issue by smaskell** [fpecune/MUF-inMind-April2017-master#49]
Earlier this morning I saw the following error from BEAT. 

`java.lang.ClassCastException: org.apache.xerces.dom.ElementNSImpl cannot be cast to org.w3c.dom.Text
java.lang.ClassCastException: org.apache.xerces.dom.ElementNSImpl cannot be cast to org.w3c.dom.Text
	at beat.scheduler.SchedulerModule.transduce(SchedulerModule.java:188)
	at beat.utilities.BeatModule.process(BeatModule.java:117)
	at beat.utilities.BeatModule.process(BeatModule.java:119)
	at beat.utilities.BeatModule.process(BeatModule.java:119)
	at beat.utilities.BeatModule.process(BeatModule.java:119)
	at beat.BEAT.startProcess(BEAT.java:146)
	at edu.cmu.inmind.multiuser.sara.component.NLGComponent.extractAndProcess(NLGComponent.java:73)
	at edu.cmu.inmind.multiuser.sara.component.NLGComponent.onEvent(NLGComponent.java:86)
	at edu.cmu.inmind.multiuser.controller.blackboard.Blackboard$1.run(Blackboard.java:243)
	`

Unfortunately, I do not yet have steps to reproduce. I will update the ticket if I see the exception again.

**Comment by timobaumann** [comment]
it would help if the exception was caught (and rethrown afterwards) some levels above and before rethrowing print out some more debug information so that we get a better grasp as to what's going wrong if/when we see this come up again.

**Comment by yoichimatsuyama** [comment]
Could you make sure that you are using a right NLU-DM (python)? I remember that we had multiple outputs from DM, and it caused the parsing error. Since we fixed that issue on AWS, we had not got this exception. This issue should be related to multiple sessions.

**Comment by smaskell** [comment]
We were connected to the NLU_DM on the server. However, it currently has vivianBranch checked out. I'm guessing this branch does not have the changes you mentioned

**Comment by timobaumann** [comment]
vivianBranch is just an extension of master (I recently rebased it). Thus, any changes are in that branch. Or is this stuff that is not pushed to github from AWS?

**Comment by timobaumann** [comment]
@yoichimatsuyama any progress on this? I think to help debugging, you could try/catch and then print whatever information could be useful to trace this before rethrowing the exception in the catch block. 
Also, you might want to put assert statements into the code to make sure that we call BEAT in an expected way (see e.g. https://docs.oracle.com/javase/8/docs/technotes/guides/language/assert.html)

Let me know if you need help with what I write above. Also, please prioritize this, our deployment is less than a week into the future and this is blocking our debugging/testing
