### ISSUE TITLE
UserModel exceptions

### ISSUE THREAD

**Issue by sushma-ananda** [fpecune/MUF-inMind-April2017-master#51]
Exception during writeModel in UserModelRepository.java trying to look for a session-id when user model does not even exist for the session-id/user.

2017-09-26 11:11:20,055 INFO    SocialReasonerComponent        - session-123	SocialReasonerComponent. These objects have been updated at the blackboard: [status: ELEMENT_ADDED, id: MSG_DM, element: Component: class edu.cmu.inmind.multiuser.sara.component.NLU_DMComponent$ActiveDMOutput System Action: ask_genres]
2017-09-26 11:11:20,056 INFO    SocialReasonerComponent        - session-123	dmOutput : Component: class edu.cmu.inmind.multiuser.sara.component.NLU_DMComponent$ActiveDMOutput System Action: ask_genres
|-- CURRENT STATE: [greeting, ask_genres, NONE_USER_CS, RAPPORT_MAINTAINED, LOW_RAPPORT, NUM_TURNS_LOWER_THAN_THRESHOLD]
|-- BEHAVIOR NETWORK CYCLE: 0
   |-- PRECONDITIONS THAT ARE TRUE (PT) AND ACTIVATION (AC) -> (PT : AC) CS: [PRECONDITIONS]
      |-- (1 : 9.200000000000001) SD: [(NUM_TURNS_LOWER_THAN_THRESHOLD, 1.0)] 
      |-- (2 : 13.36111111111111) PR: [(LOW_RAPPORT, 1.0)] [(NUM_TURNS_LOWER_THAN_THRESHOLD, 1.0)] 
      |-- (1 : 31.55555555555555) QESD: [(LOW_RAPPORT, 1.0)] 
      |-- (2 : 20.375) RSE: [(RAPPORT_MAINTAINED, 1.0)] [(greeting, 1.0)] 
      |-- (0 : 1.75) VSN: 
      |-- (2 : 16.104166666666664) ASN: [(LOW_RAPPORT, 1.0)] [(RAPPORT_MAINTAINED, 1.0)] 
      |-- (0 : 0.0) NONE: 
   |-- THETA (THRESHOLD): 15.0
   |-- EXECUTING CONVERSATIONAL STRATEGY: RSE
|-- BEHAVIOR NETWORK CYCLE: 1
   |-- PRECONDITIONS THAT ARE TRUE (PT) AND ACTIVATION (AC) -> (PT : AC) CS: [PRECONDITIONS]
      |-- (1 : 29.354404761904767) SD: [(NUM_TURNS_LOWER_THAN_THRESHOLD, 1.0)] 
      |-- (2 : 1.0) PR: [(LOW_RAPPORT, 1.0)] [(NUM_TURNS_LOWER_THAN_THRESHOLD, 1.0)] 
      |-- (1 : 50.54583333333332) QESD: [(LOW_RAPPORT, 1.0)] 
      |-- (2 : 49.71552579365079) RSE: [(RAPPORT_MAINTAINED, 1.0)] [(greeting, 1.0)] 
      |-- (0 : 2.1681547619047628) VSN: 
      |-- (2 : 58.2406356292517) ASN: [(LOW_RAPPORT, 1.0)] [(RAPPORT_MAINTAINED, 1.0)] 
      |-- (0 : 0.0) NONE: 
   |-- THETA (THRESHOLD): 15.0
   |-- EXECUTING CONVERSATIONAL STRATEGY: ASN
   |-- ELAPSED TIME: 1607ms FOR PROCESS: SocialReasoner.execute
   |-- SR OUTPUT (SORTED CONVERSATIONAL STRATEGIES): [ASN_SYSTEM_CS, RSE_SYSTEM_CS, QESD_SYSTEM_CS, SD_SYSTEM_CS, PR_SYSTEM_CS, VSN_SYSTEM_CS, NONE_SYSTEM_CS]
   |-- BLACKBOARD CONTENT: (greeting), (ask_genres), (NONE_USER_CS), (RAPPORT_MAINTAINED), (LOW_RAPPORT), (NUM_TURNS_LOWER_THAN_THRESHOLD), 2017-09-26 11:11:21,665 INFO    SocialReasonerComponent        - session-123	Input: ask_genres, Output: ASN_SYSTEM_CS

java.io.FileNotFoundException: logs/user_models/user_model_session-123.json (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.PrintWriter.<init>(PrintWriter.java:192)
	at java.io.PrintWriter.<init>(PrintWriter.java:303)
	at edu.cmu.inmind.multiuser.common.Utils.toJsonFile(Utils.java:408)
	at edu.cmu.inmind.multiuser.sara.repo.UserModelRepository.writeModel(UserModelRepository.java:37)
	at edu.cmu.inmind.multiuser.sara.component.UserModelComponent.handleMsgSR(UserModelComponent.java:105)
	at edu.cmu.inmind.multiuser.sara.component.UserModelComponent.onEvent(UserModelComponent.java:74)
	at edu.cmu.inmind.multiuser.controller.blackboard.Blackboard.lambda$notifySubscribers$0(Blackboard.java:228)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by timobaumann** [comment]
Hi Sushma, do you have the corresponding directory? (logs/user-model or what it said in the exception?)

**Comment by sushma-ananda** [comment]
HI Timo, yes I do have the directory. do you know if there is something else am missing ?

**Comment by smaskell** [comment]
I'm just using the standard Utils.toJsonFile so I'm not sure what the issue might be here. It should create the user_models directory and the json file as long as the root folder exists.

Any chance this method changed in the new version of MUF?

**Comment by sushma-ananda** [comment]
hi Samuel. no I already checked toJsonFile. its same. I figured the problem. It does not have enough permissions to create a file.  I just added. closing this. Thank you.
